name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'How are you getting on with this? If you need a hand, feel free to let us know by creating a new GitHub discussion. We are marking this as stale, but if you are still working on this, please remove the stale label or comment. Otherwise, we will close this PR in 7 days.'
        stale-pr-label: 'no-pr-activity'
        days-before-pr-stale: 7
        exempt-pr-assignees: 'knjk04'
        exempt-draft-pr: true
        # don't mark issues as stale:
        days-before-issue-stale: -1
