language: java
jdk:
- openjdk11
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: project-books
    token:
      secure: "zkktrm6WK/rcUdoaBNbJJiuhqDicXmybuw3Sw6zERgqy5RRWllCMXHQrjvHVa4pRZLQTTkUgsx4YEUOLUJaNSNW44/OqGYoiaeM99TtsH5qLw7Z8D/dVhop/BNdM1owsCrgfaVHBxIE1Bef7VsYNv+QpIKBdtkIA0qlx3elxjn37Fpnz9rZfTIoKHOTtTTH8+83ePO0ICNzXxKgoE9RIyAkQAqJcwK8T1DJSg9/seL8UHBOScrhkStuo9Ii2BIaByk9eG6N7irzX4rMEn1B6N4onlPSoh/uYPUNAQn/2EaqV97LGIbCp1oLh+nRxE0vXzu0yj9a9XuFbOxRQ2Ns8KPFKJSaLteL0RjPi9WGLOQiCDziz3KCeOnBpD59+HT8VHna5gEhAVIkpl4oIIbNGuzR88NzjNg4fGQVuAgF1OYx/NcNt6ZhmKJJWl1b6h6oNAQyYc3486gvOWMy0BxsEFptwjbNPUqf5vtq0Ha2RsBMpYCGmk+z9LrslBDnoJKSPYCFR4yVp5qCukI10JGw8yiOMMOBzfESYB1yj2pHvmoW+AwaUfEVSdOMiWBxtiuznMFZXRq92BY2JOJbbw1ik/+T4i8w/ArnoMnnUeH6vlsX3gVjrSBOwskuMreryiSlecEwQoLsws2qXeCqPhAOGb7IhowOgsFUPWbTMoctVzkc="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
