package com.karankumar.bookproject.backend.model;

// This should be kept in alphabetical order
public enum Genre {
    ADVENTURE,
    ANTHOLOGY,
    ART,
    AUTOBIOGRAPHY,
    BIOGRAPHY,
    BUSINESS,
    CHILDREN,
    CLASSIC,
    COOKBOOK,
    COMEDY,
    COMICS,
    CRIME,
    DRAMA,
    ESSAY,
    FANTASY,
    FABLE,
    FAIRY_TALE,
    FAN_FICTION,
    FICTION,
    HEALTH,
    HISTORY,
    HISTORICAL_FICTION,
    HORROR,
    MEMOIR,
    MYSTERY,
    NON_FICTION,
    PERIODICAL,
    PHILOSOPHY,
    POETRY,
    PSYCHOLOGY,
    REFERENCE,
    RELIGION,
    ROMANCE,
    SATIRE,
    SCIENCE,
    SCIENCE_FICTION,
    SELF_HELP,
    SHORT_STORY,
    SPORTS,
    THRILLER,
    TRAVEL,
    YOUNG_ADULT,
}
