ALTER TABLE book_tag
DROP FOREIGN KEY book_tag_ibfk_2;

ALTER TABLE tag
DROP PRIMARY KEY,
MODIFY id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE book_tag
ADD CONSTRAINT book_tag_id_fk FOREIGN KEY (tag_id) REFERENCES tag (id);
