ALTER TABLE book
DROP FOREIGN KEY book_author_id_fk;

ALTER TABLE author
DROP PRIMARY KEY,
MODIFY id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE book
ADD CONSTRAINT book_author_id_fk FOREIGN KEY (author_id) REFERENCES author (id);

