version: '3'

services:
  db:
    image: postgres:14 # 14 is the latest Flyway supported version
    container_name: book_project_db
    restart: always
    environment:
      - POSTGRES_DB=book_project_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    ports:
      - "5433:5432"
  bookapp:
    build: ./
    restart: on-failure      
    ports: 
      - "8080:8080"
    environment:
      - POSTGRES_DATABASE=book_project_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=5433

